const { saveDb } = require('./db_helper.js');

console.log("=== EXECUTING 3000+ TOTAL ENTRY CORPUS GENERATION ===");

// 1. MULTIPLICATION TABLES (1 to 30, up to x10) -> 300 entries
const mathTables = [];
for (let num = 1; num <= 30; num++) {
  for (let mult = 1; mult <= 10; mult++) {
    const res = num * mult;
    mathTables.push({
      id: `math-mult-table-${num}x${mult}`,
      keywords: [
        `${num} x ${mult}`,
        `${num} * ${mult}`,
        `${num} multiplied by ${mult}`,
        `${num} times ${mult}`,
        `what is ${num} x ${mult}`,
        `table of ${num}`
      ],
      title: `${num} × ${mult} = ${res} — Multiplication Table`,
      category: 'Mathematics',
      answer: `${num} multiplied by ${mult} equals ${res} (${num} × ${mult} = ${res}).`,
      highlights: [
        `Equation: ${num} × ${mult} = ${res}`,
        `Operation: Multiplication of integer ${num} by ${mult}`,
        `Table Reference: Multiplication table of ${num}`
      ],
      url: 'https://en.wikipedia.org/wiki/Multiplication_table'
    });
  }
}
saveDb('mathematics.json', mathTables);

// 2. WORLD CAPITALS & COUNTRIES EXPANSION (100 additional countries & territories)
const moreCountries = [
  ["Armenia", "Yerevan", "Armenian Dram (AMD)", "Asia/Europe", "Armenian", "3.0M", "29,743 km²"],
  ["Austria", "Vienna", "Euro (EUR)", "Europe", "German", "9.0M", "83,879 km²"],
  ["Azerbaijan", "Baku", "Azerbaijani Manat (AZN)", "Asia/Europe", "Azerbaijani", "10.1M", "86,600 km²"],
  ["Bahamas", "Nassau", "Bahamian Dollar (BSD)", "North America", "English", "400K", "13,880 km²"],
  ["Bahrain", "Manama", "Bahraini Dinar (BHD)", "Asia", "Arabic", "1.5M", "765 km²"],
  ["Bangladesh", "Dhaka", "Bangladeshi Taka (BDT)", "Asia", "Bengali", "171M", "148,460 km²"],
  ["Barbados", "Bridgetown", "Barbados Dollar (BBD)", "North America", "English", "280K", "430 km²"],
  ["Belarus", "Minsk", "Belarusian Ruble (BYN)", "Europe", "Belarusian, Russian", "9.3M", "207,600 km²"],
  ["Belgium", "Brussels", "Euro (EUR)", "Europe", "Dutch, French, German", "11.6M", "30,528 km²"],
  ["Belize", "Belmopan", "Belize Dollar (BZD)", "North America", "English", "400K", "22,966 km²"],
  ["Benin", "Porto-Novo", "West African CFA franc (XOF)", "Africa", "French", "13M", "114,763 km²"],
  ["Bhutan", "Thimphu", "Bhutanese Ngultrum (BTN)", "Asia", "Dzongkha", "780K", "38,394 km²"],
  ["Bolivia", "Sucre (constitutional), La Paz (gov)", "Boliviano (BOB)", "South America", "Spanish", "12M", "1,098,581 km²"],
  ["Bosnia and Herzegovina", "Sarajevo", "Convertible Mark (BAM)", "Europe", "Bosnian, Croatian, Serbian", "3.2M", "51,197 km²"],
  ["Botswana", "Gaborone", "Botswana Pula (BWP)", "Africa", "English, Setswana", "2.6M", "581,730 km²"],
  ["Brunei", "Bandar Seri Begawan", "Brunei Dollar (BND)", "Asia", "Malay", "450K", "5,765 km²"],
  ["Bulgaria", "Sofia", "Bulgarian Lev (BGN)", "Europe", "Bulgarian", "6.5M", "110,879 km²"],
  ["Burkina Faso", "Ouagadougou", "West African CFA franc (XOF)", "Africa", "French", "22M", "274,200 km²"],
  ["Burundi", "Gitega", "Burundian Franc (BIF)", "Africa", "Kirundi, French, English", "13M", "27,834 km²"],
  ["Cambodia", "Phnom Penh", "Cambodian Riel (KHR)", "Asia", "Khmer", "17M", "181,035 km²"],
  ["Cameroon", "Yaoundé", "Central African CFA franc (XAF)", "Africa", "French, English", "28M", "475,442 km²"],
  ["Cape Verde", "Praia", "Cape Verdean Escudo (CVE)", "Africa", "Portuguese", "590K", "4,033 km²"],
  ["Central African Republic", "Bangui", "Central African CFA franc (XAF)", "Africa", "Sango, French", "5.5M", "622,984 km²"],
  ["Chad", "N'Djamena", "Central African CFA franc (XAF)", "Africa", "French, Arabic", "18M", "1,284,000 km²"],
  ["Chile", "Santiago", "Chilean Peso (CLP)", "South America", "Spanish", "19.5M", "756,102 km²"],
  ["Colombia", "Bogotá", "Colombian Peso (COP)", "South America", "Spanish", "52M", "1,141,748 km²"],
  ["Comoros", "Moroni", "Comorian Franc (KMF)", "Africa", "Comorian, Arabic, French", "850K", "2,235 km²"],
  ["Congo, Democratic Republic", "Kinshasa", "Congolese Franc (CDF)", "Africa", "French, Lingala", "100M", "2,344,858 km²"],
  ["Congo, Republic of", "Brazzaville", "Central African CFA franc (XAF)", "Africa", "French", "6M", "342,000 km²"],
  ["Costa Rica", "San José", "Costa Rican Colón (CRC)", "North America", "Spanish", "5.2M", "51,100 km²"],
  ["Croatia", "Zagreb", "Euro (EUR)", "Europe", "Croatian", "3.9M", "56,594 km²"],
  ["Cuba", "Havana", "Cuban Peso (CUP)", "North America", "Spanish", "11M", "109,884 km²"],
  ["Cyprus", "Nicosia", "Euro (EUR)", "Europe/Asia", "Greek, Turkish", "1.2M", "9,251 km²"],
  ["Czech Republic (Czechia)", "Prague", "Czech Koruna (CZK)", "Europe", "Czech", "10.8M", "78,866 km²"],
  ["Denmark", "Copenhagen", "Danish Krone (DKK)", "Europe", "Danish", "5.9M", "43,094 km²"],
  ["Djibouti", "Djibouti", "Djiboutian Franc (DJF)", "Africa", "Arabic, French", "1.1M", "23,200 km²"],
  ["Dominica", "Roseau", "East Caribbean Dollar (XCD)", "North America", "English", "72K", "751 km²"],
  ["Dominican Republic", "Santo Domingo", "Dominican Peso (DOP)", "North America", "Spanish", "11M", "48,670 km²"],
  ["Ecuador", "Quito", "United States Dollar (USD)", "South America", "Spanish, Kichwa", "18M", "283,561 km²"],
  ["El Salvador", "San Salvador", "United States Dollar (USD)", "North America", "Spanish", "6.3M", "21,041 km²"],
  ["Equatorial Guinea", "Malabo (Oyala future)", "Central African CFA franc (XAF)", "Africa", "Spanish, French, Portuguese", "1.6M", "28,051 km²"],
  ["Eritrea", "Asmara", "Eritrean Nakfa (ERN)", "Africa", "Tigrinya, Arabic, English", "3.7M", "117,600 km²"],
  ["Estonia", "Tallinn", "Euro (EUR)", "Europe", "Estonian", "1.3M", "45,227 km²"],
  ["Eswatini (Swaziland)", "Mbabane (exec), Lobamba (leg)", "Lilangeni (SZL)", "Africa", "Swazi, English", "1.2M", "17,364 km²"],
  ["Fiji", "Suva", "Fijian Dollar (FJD)", "Oceania", "English, Fijian, Fiji Hindi", "930K", "18,274 km²"],
  ["Gabon", "Libreville", "Central African CFA franc (XAF)", "Africa", "French", "2.3M", "267,667 km²"],
  ["Gambia", "Banjul", "Gambian Dalasi (GMD)", "Africa", "English", "2.7M", "10,689 km²"],
  ["Georgia", "Tbilisi", "Georgian Lari (GEL)", "Asia/Europe", "Georgian", "3.7M", "69,700 km²"],
  ["Ghana", "Accra", "Ghanaian Cedi (GHS)", "Africa", "English", "34M", "238,533 km²"],
  ["Guatemala", "Guatemala City", "Guatemalan Quetzal (GTQ)", "North America", "Spanish", "18M", "108,889 km²"],
  ["Guinea", "Conakry", "Guinean Franc (GNF)", "Africa", "French", "14M", "245,857 km²"],
  ["Guinea-Bissau", "Bissau", "West African CFA franc (XOF)", "Africa", "Portuguese", "2.1M", "36,125 km²"],
  ["Guyana", "Georgetown", "Guyanese Dollar (GYD)", "South America", "English", "800K", "214,969 km²"],
  ["Haiti", "Port-au-Prince", "Haitian Gourde (HTG)", "North America", "Haitian Creole, French", "11.5M", "27,750 km²"],
  ["Honduras", "Tegucigalpa", "Honduran Lempira (HNL)", "North America", "Spanish", "10.4M", "112,492 km²"],
  ["Hungary", "Budapest", "Hungarian Forint (HUF)", "Europe", "Hungarian", "9.6M", "93,030 km²"],
  ["Iceland", "Reykjavík", "Icelandic Króna (ISK)", "Europe", "Icelandic", "380K", "103,000 km²"],
  ["Ivory Coast (Côte d'Ivoire)", "Yamoussoukro", "West African CFA franc (XOF)", "Africa", "French", "29M", "322,463 km²"],
  ["Jamaica", "Kingston", "Jamaican Dollar (JMD)", "North America", "English", "2.8M", "10,991 km²"],
  ["Jordan", "Amman", "Jordanian Dinar (JOD)", "Asia", "Arabic", "11M", "89,342 km²"],
  ["Kazakhstan", "Astana", "Kazakhstani Tenge (KZT)", "Asia/Europe", "Kazakh, Russian", "20M", "2,724,900 km²"],
  ["Kuwait", "Kuwait City", "Kuwaiti Dinar (KWD)", "Asia", "Arabic", "4.3M", "17,818 km²"],
  ["Kyrgyzstan", "Bishkek", "Kyrgyzstani Som (KGS)", "Asia", "Kyrgyz, Russian", "7.0M", "199,951 km²"],
  ["Laos", "Vientiane", "Lao Kip (LAK)", "Asia", "Lao", "7.5M", "236,800 km²"],
  ["Latvia", "Riga", "Euro (EUR)", "Europe", "Latvian", "1.9M", "64,589 km²"],
  ["Lebanon", "Beirut", "Lebanese Pound (LBP)", "Asia", "Arabic", "5.5M", "10,452 km²"],
  ["Lesotho", "Maseru", "Lesotho Loti (LSL)", "Africa", "Sesotho, English", "2.3M", "30,355 km²"],
  ["Liberia", "Monrovia", "Liberian Dollar (LRD)", "Africa", "English", "5.3M", "111,369 km²"],
  ["Libya", "Tripoli", "Libyan Dinar (LYD)", "Africa", "Arabic", "7.0M", "1,759,540 km²"],
  ["Liechtenstein", "Vaduz", "Swiss Franc (CHF)", "Europe", "German", "39K", "160 km²"],
  ["Lithuania", "Vilnius", "Euro (EUR)", "Europe", "Lithuanian", "2.8M", "65,300 km²"],
  ["Luxembourg", "Luxembourg City", "Euro (EUR)", "Europe", "Luxembourgish, French, German", "660K", "2,586 km²"],
  ["Madagascar", "Antananarivo", "Malagasy Ariary (MGA)", "Africa", "Malagasy, French", "29M", "587,041 km²"],
  ["Malawi", "Lilongwe", "Malawian Kwacha (MWK)", "Africa", "English, Chichewa", "20M", "118,484 km²"],
  ["Malaysia", "Kuala Lumpur (Putrajaya seat)", "Malaysian Ringgit (MYR)", "Asia", "Malay", "34M", "330,803 km²"],
  ["Maldives", "Malé", "Maldivian Rufiyaa (MVR)", "Asia", "Dhivehi", "520K", "298 km²"],
  ["Mali", "Bamako", "West African CFA franc (XOF)", "Africa", "Bambara, French", "22M", "1,240,192 km²"],
  ["Malta", "Valletta", "Euro (EUR)", "Europe", "Maltese, English", "530K", "316 km²"],
  ["Mauritania", "Nouakchott", "Mauritanian Ouguiya (MRU)", "Africa", "Arabic", "4.8M", "1,030,700 km²"],
  ["Mauritius", "Port Louis", "Mauritian Rupee (MUR)", "Africa", "English, French, Mauritian Creole", "1.3M", "2,040 km²"],
  ["Moldova", "Chișinău", "Moldovan Leu (MDL)", "Europe", "Romanian", "2.5M", "33,846 km²"],
  ["Monaco", "Monaco", "Euro (EUR)", "Europe", "French", "39K", "2.08 km²"],
  ["Mongolia", "Ulaanbaatar", "Mongolian Tögrög (MNT)", "Asia", "Mongolian", "3.4M", "1,564,116 km²"],
  ["Montenegro", "Podgorica", "Euro (EUR)", "Europe", "Montenegrin", "620K", "13,812 km²"],
  ["Morocco", "Rabat", "Moroccan Dirham (MAD)", "Africa", "Arabic, Berber", "37M", "446,550 km²"],
  ["Mozambique", "Maputo", "Mozambican Metical (MZN)", "Africa", "Portuguese", "33M", "801,590 km²"],
  ["Myanmar (Burma)", "Naypyidaw", "Myanmar Kyat (MMK)", "Asia", "Burmese", "54M", "676,578 km²"],
  ["Namibia", "Windhoek", "Namibian Dollar (NAD)", "Africa", "English", "2.6M", "825,615 km²"],
  ["Nauru", "Yaren (de facto)", "Australian Dollar (AUD)", "Oceania", "Nauruan, English", "12K", "21 km²"],
  ["Nicaragua", "Managua", "Nicaraguan Córdoba (NIO)", "North America", "Spanish", "7.0M", "130,373 km²"],
  ["Niger", "Niamey", "West African CFA franc (XOF)", "Africa", "French", "26M", "1,267,000 km²"],
  ["North Macedonia", "Skopje", "Macedonian Denar (MKD)", "Europe", "Macedonian, Albanian", "1.8M", "25,713 km²"],
  ["Norway", "Oslo", "Norwegian Krone (NOK)", "Europe", "Norwegian", "5.5M", "385,207 km²"],
  ["Oman", "Muscat", "Omani Rial (OMR)", "Asia", "Arabic", "4.6M", "309,500 km²"],
  ["Panama", "Panama City", "Panamanian Balboa (PAB) / USD", "North America", "Spanish", "4.4M", "75,417 km²"],
  ["Papua New Guinea", "Port Moresby", "Papua New Guinean Kina (PGK)", "Oceania", "English, Tok Pisin, Hiri Motu", "10M", "462,840 km²"],
  ["Paraguay", "Asunción", "Paraguayan Guaraní (PYG)", "South America", "Spanish, Guaraní", "6.8M", "406,752 km²"],
  ["Peru", "Lima", "Peruvian Sol (PEN)", "South America", "Spanish, Quechua", "34M", "1,285,216 km²"],
  ["Philippines", "Manila", "Philippine Peso (PHP)", "Asia", "Filipino, English", "115M", "300,000 km²"],
  ["Poland", "Warsaw", "Polish Złoty (PLN)", "Europe", "Polish", "38M", "312,696 km²"],
  ["Portugal", "Lisbon", "Euro (EUR)", "Europe", "Portuguese", "10.4M", "92,212 km²"],
  ["Qatar", "Doha", "Qatari Riyal (QAR)", "Asia", "Arabic", "3.0M", "11,586 km²"],
  ["Romania", "Bucharest", "Romanian Leu (RON)", "Europe", "Romanian", "19M", "238,397 km²"],
  ["Rwanda", "Kigali", "Rwandan Franc (RWF)", "Africa", "Kinyarwanda, French, English", "13.5M", "26,338 km²"],
  ["Saint Kitts and Nevis", "Basseterre", "East Caribbean Dollar (XCD)", "North America", "English", "48K", "261 km²"],
  ["Saint Lucia", "Castries", "East Caribbean Dollar (XCD)", "North America", "English", "180K", "616 km²"],
  ["Saint Vincent and the Grenadines", "Kingstown", "East Caribbean Dollar (XCD)", "North America", "English", "104K", "389 km²"],
  ["Samoa", "Apia", "Samoan Tālā (WST)", "Oceania", "Samoan, English", "220K", "2,842 km²"],
  ["San Marino", "San Marino", "Euro (EUR)", "Europe", "Italian", "34K", "61 km²"],
  ["Sao Tome and Principe", "São Tomé", "São Tomé Dobra (STN)", "Africa", "Portuguese", "230K", "964 km²"],
  ["Senegal", "Dakar", "West African CFA franc (XOF)", "Africa", "French, Wolof", "17M", "196,722 km²"],
  ["Serbia", "Belgrade", "Serbian Dinar (RSD)", "Europe", "Serbian", "6.6M", "88,361 km²"],
  ["Seychelles", "Victoria", "Seychellois Rupee (SCR)", "Africa", "Seychellois Creole, English, French", "100K", "459 km²"],
  ["Sierra Leone", "Freetown", "Sierra Leonean Leone (SLE)", "Africa", "English", "8.6M", "71,740 km²"],
  ["Slovakia", "Bratislava", "Euro (EUR)", "Europe", "Slovak", "5.4M", "49,035 km²"],
  ["Slovenia", "Ljubljana", "Euro (EUR)", "Europe", "Slovene", "2.1M", "20,273 km²"],
  ["Solomon Islands", "Honiara", "Solomon Islands Dollar (SBD)", "Oceania", "English", "720K", "28,896 km²"],
  ["Somalia", "Mogadishu", "Somali Shilling (SOS)", "Africa", "Somali, Arabic", "17M", "637,657 km²"],
  ["South Sudan", "Juba", "South Sudanese Pound (SSP)", "Africa", "English", "11M", "644,329 km²"],
  ["Sri Lanka", "Sri Jayawardenepura Kotte (admin), Colombo (comm)", "Sri Lankan Rupee (LKR)", "Asia", "Sinhala, Tamil", "22M", "65,610 km²"],
  ["Sudan", "Khartoum", "Sudanese Pound (SDG)", "Africa", "Arabic, English", "46M", "1,861,484 km²"],
  ["Suriname", "Paramaribo", "Surinamese Dollar (SRD)", "South America", "Dutch", "620K", "163,820 km²"],
  ["Sweden", "Stockholm", "Swedish Krona (SEK)", "Europe", "Swedish", "10.5M", "450,295 km²"],
  ["Switzerland", "Bern", "Swiss Franc (CHF)", "Europe", "German, French, Italian, Romansh", "8.8M", "41,285 km²"],
  ["Syria", "Damascus", "Syrian Pound (SYP)", "Asia", "Arabic", "22M", "185,180 km²"],
  ["Taiwan", "Taipei", "New Taiwan Dollar (TWD)", "Asia", "Mandarin", "23.5M", "36,197 km²"],
  ["Tajikistan", "Dushanbe", "Tajikistani Somoni (TJS)", "Asia", "Tajik", "10M", "143,100 km²"],
  ["Tanzania", "Dodoma (Dar es Salaam comm)", "Tanzanian Shilling (TZS)", "Africa", "Swahili, English", "65M", "947,303 km²"],
  ["Thailand", "Bangkok", "Thai Baht (THB)", "Asia", "Thai", "72M", "513,120 km²"],
  ["Timor-Leste (East Timor)", "Dili", "United States Dollar (USD)", "Asia", "Tetum, Portuguese", "1.3M", "14,919 km²"],
  ["Togo", "Lomé", "West African CFA franc (XOF)", "Africa", "French", "8.8M", "56,785 km²"],
  ["Tonga", "Nukuʻalofa", "Tongan Paʻanga (TOP)", "Oceania", "Tongan, English", "106K", "747 km²"],
  ["Trinidad and Tobago", "Port of Spain", "Trinidad and Tobago Dollar (TTD)", "North America", "English", "1.5M", "5,130 km²"],
  ["Tunisia", "Tunis", "Tunisian Dinar (TND)", "Africa", "Arabic", "12M", "163,610 km²"],
  ["Turkey (Türkiye)", "Ankara (Istanbul largest)", "Turkish Lira (TRY)", "Asia/Europe", "Turkish", "85M", "783,562 km²"],
  ["Turkmenistan", "Ashgabat", "Turkmenistan Manat (TMT)", "Asia", "Turkmen", "6.5M", "488,100 km²"],
  ["Tuvalu", "Funafuti", "Tuvaluan Dollar (TVD) / AUD", "Oceania", "Tuvaluan, English", "11K", "26 km²"],
  ["Uganda", "Kampala", "Ugandan Shilling (UGX)", "Africa", "English, Swahili", "47M", "241,038 km²"],
  ["Ukraine", "Kyiv", "Ukrainian Hryvnia (UAH)", "Europe", "Ukrainian", "38M", "603,628 km²"],
  ["Uruguay", "Montevideo", "Uruguayan Peso (UYU)", "South America", "Spanish", "3.4M", "176,215 km²"],
  ["Uzbekistan", "Tashkent", "Uzbekistani Som (UZS)", "Asia", "Uzbek", "36M", "447,400 km²"],
  ["Vanuatu", "Port Vila", "Vanuatu Vatu (VUV)", "Oceania", "Bislama, English, French", "320K", "12,189 km²"],
  ["Vatican City", "Vatican City", "Euro (EUR)", "Europe", "Italian, Latin", "800", "0.49 km²"],
  ["Venezuela", "Caracas", "Venezuelan Bolívar (VES)", "South America", "Spanish", "28M", "916,445 km²"],
  ["Vietnam", "Hanoi (Ho Chi Minh largest)", "Vietnamese Đồng (VND)", "Asia", "Vietnamese", "98M", "331,212 km²"],
  ["Yemen", "Sana'a (Aden temp)", "Yemeni Rial (YER)", "Asia", "Arabic", "33M", "527,968 km²"],
  ["Zambia", "Lusaka", "Zambian Kwacha (ZMW)", "Africa", "English", "20M", "752,618 km²"],
  ["Zimbabwe", "Harare", "Zimbabwe Gold (ZiG) / USD", "Africa", "16 official languages (Shona, Ndebele, English...)", "16M", "390,757 km²"]
];

const countryExpandedNodes = moreCountries.map(c => {
  const [name, cap, curr, cont, lang, pop, area] = c;
  return {
    id: `geo-country-full-${name.toLowerCase().replace(/[^\w]/g, '-')}`,
    keywords: [
      `capital of ${name.toLowerCase()}`,
      `currency of ${name.toLowerCase()}`,
      `${name.toLowerCase()} capital`,
      `${name.toLowerCase()} currency`,
      `where is ${name.toLowerCase()}`,
      `${name.toLowerCase()} facts`
    ],
    title: `${name} — Capital: ${cap} | Currency: ${curr}`,
    category: 'Geography',
    answer: `${name} is a sovereign country in ${cont} with capital ${cap} and official currency ${curr}. Population is approximately ${pop}, covering an area of ${area}. Official language(s): ${lang}.`,
    highlights: [
      `Country: ${name}`,
      `Capital: ${cap}`,
      `Currency: ${curr}`,
      `Continent: ${cont}`,
      `Official Language(s): ${lang}`,
      `Population: ~${pop} | Area: ${area}`
    ],
    url: `https://en.wikipedia.org/wiki/${name.split(' ')[0]}`
  };
});
saveDb('world_geography_advanced.json', countryExpandedNodes);

console.log("3000+ Corpus batch completed successfully.");